title: 465woerter
description: © 2018 - Valeska Geesdorf, va.ge@posteo.de
site.lang: de-DE

show_downloads: false
google_analytics:
theme: jekyll-theme-midnight

collections:
  mensch:
    output: true
    title: mensch
  luecke:
    output: true
    title: lücke
  stadt:
    output: true
    title: stadt
  koerper:
    output: true
    title: körper

# baseurl: "/465woerter"

permalink: none

plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji

sass:
  style: compressed
