title: 465woerter
description: © 2018- Valeska Geesdorf, va.ge@posteo.de.

show_downloads: false
google_analytics:
theme: jekyll-theme-midnight

collections:
  mensch:
    output: true
  lücke:
    output: true
  stadt:
    output: true
  körper:
    output: true
    
baseurl: "/465woerter"

permalink: none

plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji

sass:
  style: compressed
