theme: jekyll-theme-midnight

collections:
  mensch:
    output: true
  lücke:
    output: true
  stadt:
    output: true
  körper:
    output: true
    
# baseurl: "/"

permalink: none

plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji

sass:
  style: compressed
