title: 465woerter
description: © 2018-2019 - Valeska Geesdorf, va.ge@posteo.de
site.lang: de-DE

show_downloads: false
google_analytics:
theme: jekyll-theme-midnight

collections:
  sinn:
    output: true
    title: sinn
  mensch:
    output: true
    title: mensch
  luecke:
    output: true
    title: lücke
  lust:
    output: true
    title: lust
  koerper:
    output: true
    title: körper
  stadt:
    output: true
    title: stadt

# baseurl: "https://465woerter.de/"

permalink: none

plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji

sass:
  style: compressed
